name: CI

on:
  push:
    branches:
      - "*"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event.base_ref != 'refs/heads/main'
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3.1.0

      - name: Install php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.8'
          coverage: xdebug

      - name: Install npm
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.16.1

      - name: Install php requirements
        run: |
          cd src
          composer install

      - name: Install npm dependencies
        run: |
          cd src
          npm ci

      - name: Generate .env file
        run: |
          cd src
          cp .env.example .env
          php artisan key:generate
          cp .env .env.testing
          sed -i -e "s/DISCORD_APPLICATION_ID=/DISCORD_APPLICATION_ID=DISCORD_APPLICATION_ID/g" .env.testing

      - name: Build assets
        run: |
          cd src
          npm run build

      - name: Run test
        run: |
          cd src
          php artisan test --coverage
#          php artisan test --coverage --min=90