name: CI

on:
  push:
    branches:
      - "*"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event.base_ref != 'refs/heads/main'
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3.1.0

      - name: Install php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.8'
          coverage: xdebug

      - name: Install npm
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.16.1

      - name: Install npm dependencies
        run: npm ci

      - name: Prepare The Environment
        run: |
          cp .env.example .env
          sed -i -e "s/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/g" .env
          sed -i '/DB_HOST/d' .env
          sed -i '/DB_PORT/d' .env
          sed -i '/DB_DATABASE/d' .env
          sed -i '/DB_USERNAME/d' .env
          sed -i '/DB_PASSWORD/d' .env

      - name: Create Database
        run: |
          touch /home/runner/work/fitness/fitness/database/database.sqlite

      - name: Install php requirements
        run: composer install

      - name: Generate Application Key
        run: |
          php artisan key:generate
          sed -i -e "s/DISCORD_APPLICATION_ID=/DISCORD_APPLICATION_ID=DISCORD_APPLICATION_ID/g" .env
          cp .env .env.dusk.local
          cp .env .env.testing

      - name: Build assets
        run: npm run build

      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver --all

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux &

      - name: Run Laravel Server
        run: php artisan serve --no-reload &

      - name: Run Dusk Tests
        run: php artisan dusk

      - name: Run test
        run: php artisan test --coverage --min=90

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
