name: CI

on:
  push:
    branches:
      - "*"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event.base_ref != 'refs/heads/main'
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3.1.0

      - uses: shivammathur/setup-php@v2.25.4
        with:
          php-version: '8.2.7'
          tools: none

      - name: Install php requirements
        run: |
          cd src
          composer install

      - name: Run test
        run: |
          cd src
          php artisan test --coverage --min=90
